language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - npm set progress=false
before_script:
  - npm prune
script:
  - npm run test -- --reporter=dot
  - npm run build
after_success:
  - npm run check-coverage
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
