language: node_js
cache:
  yarn: true
  directories:
    - node_modules
os:
  - linux
  - osx
script:
  - npm run test -- --reporter=dot --check-leaks
  - npm run build
after_success:
  - npm run check-coverage
