sudo: false
language: node_js
cache:
  directories:
    - node_modules
before_install:
  - npm set progress=false
script:
  - npm run test -- --reporter=dot
  - npm run build
after_success:
  - npm run check-coverage
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
